packages:
  - packages/*

catalogs:
  runtime:
    ansi-colors: ^4.1.3
    commander: ^14.0.0
    execa: ^9.6.0
    zod: ^4.1.12
  build:
    '@types/node': ^24.1.0
    '@vitest/ui': ^2.1.8
    tsdown: ^0.18.0
    typescript: ^5.9.3
    vitest: ^2.1.8

onlyBuiltDependencies:
  - esbuild
