/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * Any manual changes will be overwritten by the automation.
 *
 * To modify these tests, update the specification files:
 * - /docs/E2E_TESTS.md (root-level testing philosophy and constraints)
 * - /packages/cli/E2E_TESTS.md (CLI-specific test specifications)
 *
 * Then run the /update-e2e-tests command to regenerate this file.
 * ============================================================================
 */

/**
 * E2E Test Utilities
 *
 * This module provides shared utilities for e2e tests, including
 * environment-based test filtering for mock vs real agent tests.
 */

/**
 * When true, tests that require real AI agent execution should run.
 * Set ROVER_E2E_REAL_AGENT=true to enable real agent tests.
 *
 * Usage in tests:
 * ```ts
 * import { SKIP_REAL_AGENT_TESTS } from './e2e-utils';
 *
 * describe.skipIf(SKIP_REAL_AGENT_TESTS)('my real agent test', () => { ... });
 * ```
 */
export const REAL_AGENT_MODE = process.env.ROVER_E2E_REAL_AGENT === 'true';

/**
 * Condition for skipping tests that require real AI agent execution.
 * Use with vitest's skipIf:
 *
 * ```ts
 * describe.skipIf(SKIP_REAL_AGENT_TESTS)('requires real agent', () => { ... });
 * ```
 */
export const SKIP_REAL_AGENT_TESTS = !REAL_AGENT_MODE;

/**
 * Condition for skipping tests that only work with mock agents.
 * Use with vitest's skipIf when you want to run ONLY real agent tests:
 *
 * ```ts
 * describe.skipIf(SKIP_MOCK_TESTS)('mock-only test', () => { ... });
 * ```
 */
export const SKIP_MOCK_TESTS = REAL_AGENT_MODE;

import { rmSync } from 'node:fs';

/**
 * Safely remove a directory tree, tolerating filesystem race conditions.
 *
 * Node.js's internal rimraf implementation used by `rmSync` can spuriously
 * fail with ENOTEMPTY on Linux (and Windows) because `rmdir` may be called
 * before preceding `unlink` operations have fully propagated at the VFS
 * level. See: https://github.com/nodejs/node/issues/41201
 *
 * This helper uses `maxRetries` / `retryDelay` as a best effort and
 * swallows any remaining errors so that cleanup failures in afterEach
 * hooks never cause test failures. The directories live under /tmp and
 * will be reclaimed by the OS regardless.
 */
export function safeCleanup(dir: string): void {
  try {
    rmSync(dir, {
      recursive: true,
      force: true,
      maxRetries: 5,
      retryDelay: 500,
    });
  } catch {
    // Best-effort cleanup — see JSDoc above.
  }
}

/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * To modify these tests, update the specification files:
 * - /docs/E2E_TESTS.md (root-level testing philosophy and constraints)
 * - /packages/cli/E2E_TESTS.md (CLI-specific test specifications)
 *
 * Then run the /update-e2e-tests command to regenerate this file.
 * ============================================================================
 */
