/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * Any manual changes will be overwritten by the automation.
 *
 * To modify these tests, update the specification files:
 * - /docs/E2E_TESTS.md (root-level testing philosophy and constraints)
 * - /packages/cli/E2E_TESTS.md (CLI-specific test specifications)
 *
 * Then run the /update-e2e-tests command to regenerate this file.
 * ============================================================================
 */

import { beforeEach, afterEach, describe, it, expect } from 'vitest';
import { SKIP_REAL_AGENT_TESTS } from './e2e-utils.js';
import {
  mkdtempSync,
  rmSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  chmodSync,
  readdirSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execa } from 'execa';

/**
 * E2E tests for `rover iterate` (alias `rover iter`) command
 *
 * These tests run the actual rover CLI binary and test the full task iteration workflow.
 * They mock system tool availability by creating wrapper scripts in a temporary bin directory.
 */

describe('rover iterate (e2e)', () => {
  let testDir: string;
  let originalCwd: string;
  let mockBinDir: string;
  let mockHomeDir: string;
  let originalPath: string;

  const createMockTool = (
    toolName: string,
    exitCode: number = 0,
    output: string = 'mock version 1.0.0'
  ) => {
    const scriptPath = join(mockBinDir, toolName);
    const scriptContent = `#!/usr/bin/env bash\necho "${output}"\nexit ${exitCode}`;
    writeFileSync(scriptPath, scriptContent);
    chmodSync(scriptPath, 0o755);
  };

  const createMockScript = (toolName: string, scriptContent: string) => {
    const scriptPath = join(mockBinDir, toolName);
    writeFileSync(scriptPath, scriptContent);
    chmodSync(scriptPath, 0o755);
  };

  const createMockClaude = () => {
    createMockScript(
      'claude',
      `#!/usr/bin/env bash
if [[ "$1" == "--version" ]]; then
  echo "Claude CLI v1.0.0"
  exit 0
fi

if [[ "$1" == "-p" ]]; then
  PROMPT=$(cat)
  if [[ "$2" == "--output-format" && "$3" == "json" ]]; then
    echo '{"result":"{\\"title\\":\\"Test task\\",\\"description\\":\\"A test task description.\\"}"}'
  else
    echo '{"title":"Test task","description":"A test task description."}'
  fi
  exit 0
fi

echo "Claude CLI v1.0.0"
exit 0
`
    );
  };

  const roverBin = join(__dirname, '../../../dist/index.mjs');

  const runRover = async (args: string[]) => {
    const testPath = `${mockBinDir}:${originalPath}`;
    return execa('node', [roverBin, ...args], {
      cwd: testDir,
      env: {
        PATH: testPath,
        HOME: mockHomeDir,
        USER: process.env.USER,
        TMPDIR: process.env.TMPDIR,
        ROVER_NO_TELEMETRY: '1',
      },
      reject: false,
    });
  };

  const waitForTaskStatus = async (
    taskId: number,
    expectedStatuses: string[],
    timeoutMs: number = 600000
  ): Promise<string> => {
    const startTime = Date.now();
    while (Date.now() - startTime < timeoutMs) {
      const result = await runRover(['inspect', String(taskId), '--json']);
      if (result.exitCode === 0) {
        const output = JSON.parse(result.stdout);
        if (expectedStatuses.includes(output.status)) return output.status;
      }
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
    throw new Error(
      `Timeout waiting for task ${taskId} to reach one of statuses: ${expectedStatuses.join(', ')}`
    );
  };

  beforeEach(async () => {
    originalCwd = process.cwd();
    originalPath = process.env.PATH || '';

    testDir = mkdtempSync(join(tmpdir(), 'rover-iterate-e2e-'));
    process.chdir(testDir);

    mockBinDir = join(testDir, '.mock-bin');
    mkdirSync(mockBinDir, { recursive: true });

    // Create mock HOME directory with agent configuration files
    mockHomeDir = join(testDir, '.mock-home');
    mkdirSync(mockHomeDir, { recursive: true });
    writeFileSync(
      join(mockHomeDir, '.claude.json'),
      JSON.stringify({ version: 1 })
    );

    process.env.PATH = `${mockBinDir}:${originalPath}`;

    createMockTool('docker', 127, 'command not found: docker');
    createMockTool('claude', 127, 'command not found: claude');
    createMockTool('codex', 127, 'command not found: codex');
    createMockTool('cursor', 127, 'command not found: cursor');
    createMockTool('cursor-agent', 127, 'command not found: cursor-agent');
    createMockTool('gemini', 127, 'command not found: gemini');
    createMockTool('qwen', 127, 'command not found: qwen');
    createMockTool('opencode', 127, 'command not found: opencode');

    createMockTool('docker', 0, 'Docker version 24.0.0');
    createMockClaude();

    await execa('git', ['init']);
    await execa('git', ['config', 'user.email', 'test@test.com']);
    await execa('git', ['config', 'user.name', 'Test User']);
    await execa('git', ['config', 'commit.gpgsign', 'false']);

    writeFileSync(
      'package.json',
      JSON.stringify(
        { name: 'test-project', version: '1.0.0', type: 'module' },
        null,
        2
      )
    );
    writeFileSync('README.md', '# Test Project\n');

    await execa('git', ['add', '.']);
    await execa('git', ['commit', '-m', 'Initial commit']);

    await runRover(['init', '--yes']);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    process.env.PATH = originalPath;
    rmSync(testDir, { recursive: true, force: true });
  });

  /**
   * SKIPPED: Tests require real AI agent execution
   *
   * Why skipped:
   *   These tests use waitForTaskStatus which polls until a task reaches IN_PROGRESS,
   *   COMPLETED, or FAILED status. With mock Docker, containers don't actually run,
   *   so tasks never transition past the initial state.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Ensure Docker is running and can pull the rover agent image
   *   3. Ensure a valid AI agent (Claude CLI, Gemini CLI, etc.) is installed and authenticated
   *   4. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "instruction-based iteration"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)('instruction-based iteration', () => {
    // This test requires a real agent to make progress in the container.
    // The mock Docker doesn't run real containers, so tasks never reach COMPLETED status.
    it('should create a new iteration with refinement instructions', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskStatus(1, ['COMPLETED', 'FAILED']);
      const result = await runRover([
        'iterate',
        '1',
        'Please also add error handling to the script',
        '--json',
      ]);
      expect(result.exitCode).toBeDefined();
    });

    it('should not allow iteration on a currently running task', async () => {
      // Create a task
      await runRover(['task', '-y', 'Create a hello world script']);

      // Wait for it to be in progress
      await waitForTaskStatus(1, ['IN_PROGRESS']);

      // Try to iterate on a running task
      const result = await runRover([
        'iterate',
        '1',
        'Add error handling',
        '--json',
      ]);

      // Should fail because the task is running
      expect(result.exitCode).not.toBe(0);
    });
  });

  /**
   * SKIPPED: Tests require real AI agent execution
   *
   * Why skipped:
   *   Iteration numbering tests require tasks to complete multiple iterations.
   *   With mock Docker, no real agent execution occurs, so iterations don't progress.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Ensure Docker is running and can pull the rover agent image
   *   3. Ensure a valid AI agent (Claude CLI, Gemini CLI, etc.) is installed and authenticated
   *   4. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "iteration numbering"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)('iteration numbering', () => {
    it('should increment iteration numbers for each new iteration', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskStatus(1, ['COMPLETED', 'FAILED']);

      const inspectBefore = await runRover(['inspect', '1', '--json']);
      expect(inspectBefore.exitCode).toBe(0);
      const taskBefore = JSON.parse(inspectBefore.stdout);
      const initialIterations = taskBefore.iterations || 1;

      const iterateResult = await runRover([
        'iterate',
        '1',
        'Add error handling',
      ]);
      expect(iterateResult.exitCode).toBe(0);

      await waitForTaskStatus(1, ['COMPLETED', 'FAILED', 'ITERATING']);

      const inspectAfter = await runRover(['inspect', '1', '--json']);
      expect(inspectAfter.exitCode).toBe(0);
      const taskAfter = JSON.parse(inspectAfter.stdout);
      expect(taskAfter.iterations).toBeGreaterThan(initialIterations);
    });

    it('should preserve previous iteration outputs', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskStatus(1, ['COMPLETED', 'FAILED']);

      // Run first iteration
      await runRover(['iterate', '1', 'Add error handling']);
      await waitForTaskStatus(1, ['COMPLETED', 'FAILED']);

      // Inspect to verify iteration directory exists
      const inspectResult = await runRover(['inspect', '1', '--json']);
      expect(inspectResult.exitCode).toBe(0);

      const task = JSON.parse(inspectResult.stdout);
      expect(task.iterations).toBeGreaterThanOrEqual(2);
    });
  });

  describe('interactive iteration', () => {
    it('should have --interactive flag available for shell session inside sandbox', async () => {
      // Verify the iterate command has the --interactive flag by checking help output
      const helpResult = await runRover(['iterate', '--help']);

      expect(helpResult.exitCode).toBe(0);
      expect(helpResult.stdout).toContain('--interactive');
    });

    it('should have -i shorthand for --interactive flag', async () => {
      // Verify the -i shorthand is documented
      const helpResult = await runRover(['iterate', '--help']);

      expect(helpResult.exitCode).toBe(0);
      // Check for either -i or --interactive in help output
      expect(helpResult.stdout).toMatch(/-i.*--interactive|--interactive.*-i/s);
    });
  });

  describe('alias support', () => {
    it('should recognize the iter alias', async () => {
      // Verify the iter alias is recognized by checking help output
      const helpResult = await runRover(['iter', '--help']);

      expect(helpResult.exitCode).toBe(0);
      expect(helpResult.stdout).toContain('iterate');
    });

    it('should require a task ID when using the iter alias', async () => {
      // Using iter without a task ID should fail gracefully
      const result = await runRover(['iter']);

      // Should fail because no task ID was provided
      expect(result.exitCode).not.toBe(0);
    });

    it('should report error for non-existent task with iter alias', async () => {
      // Create a task first so the project is properly initialized
      await runRover(['task', '-y', 'Create a hello world script', '--json']);

      // Try to iterate on a non-existent task using the alias
      const result = await runRover([
        'iter',
        '999',
        'Add error handling',
        '--json',
      ]);

      // Should fail because task 999 doesn't exist
      expect(result.exitCode).not.toBe(0);
    });
  });
});
