/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * Any manual changes will be overwritten by the automation.
 *
 * To modify these tests, update the specification files:
 * - /E2E_TESTS.md (root-level testing philosophy and constraints)
 * - /packages/cli/E2E_TESTS.md (CLI-specific test specifications)
 *
 * Then run the /update-e2e-tests command to regenerate this file.
 * ============================================================================
 */

import { beforeEach, afterEach, describe, it, expect } from 'vitest';
import { SKIP_REAL_AGENT_TESTS } from './e2e-utils.js';
import {
  mkdtempSync,
  rmSync,
  writeFileSync,
  readFileSync,
  existsSync,
  mkdirSync,
  chmodSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execa } from 'execa';

/**
 * E2E tests for `rover merge` command
 *
 * These tests run the actual rover CLI binary and test the full task merge workflow.
 * They mock system tool availability by creating wrapper scripts in a temporary bin directory.
 */

describe('rover merge (e2e)', () => {
  let testDir: string;
  let originalCwd: string;
  let mockBinDir: string;
  let mockHomeDir: string;
  let originalPath: string;

  const createMockTool = (
    toolName: string,
    exitCode: number = 0,
    output: string = 'mock version 1.0.0'
  ) => {
    const scriptPath = join(mockBinDir, toolName);
    const scriptContent = `#!/usr/bin/env bash\necho "${output}"\nexit ${exitCode}`;
    writeFileSync(scriptPath, scriptContent);
    chmodSync(scriptPath, 0o755);
  };

  const createMockScript = (toolName: string, scriptContent: string) => {
    const scriptPath = join(mockBinDir, toolName);
    writeFileSync(scriptPath, scriptContent);
    chmodSync(scriptPath, 0o755);
  };

  const createMockClaude = () => {
    createMockScript(
      'claude',
      `#!/usr/bin/env bash
if [[ "$1" == "--version" ]]; then
  echo "Claude CLI v1.0.0"
  exit 0
fi

if [[ "$1" == "-p" ]]; then
  PROMPT=$(cat)
  if [[ "$2" == "--output-format" && "$3" == "json" ]]; then
    echo '{"result":"{\\"title\\":\\"Test task\\",\\"description\\":\\"A test task description.\\"}"}'
  else
    echo '{"title":"Test task","description":"A test task description."}'
  fi
  exit 0
fi

echo "Claude CLI v1.0.0"
exit 0
`
    );
  };

  const roverBin = join(__dirname, '../../../dist/index.mjs');

  const runRover = async (args: string[]) => {
    const testPath = `${mockBinDir}:${originalPath}`;
    return execa('node', [roverBin, ...args], {
      cwd: testDir,
      env: {
        PATH: testPath,
        HOME: mockHomeDir,
        USER: process.env.USER,
        TMPDIR: process.env.TMPDIR,
        ROVER_NO_TELEMETRY: '1',
      },
      reject: false,
    });
  };

  const waitForTaskCompletion = async (
    taskId: number,
    timeoutMs: number = 600000
  ): Promise<void> => {
    const startTime = Date.now();
    while (Date.now() - startTime < timeoutMs) {
      const result = await runRover(['inspect', String(taskId), '--json']);
      if (result.exitCode === 0) {
        const output = JSON.parse(result.stdout);
        if (output.status === 'COMPLETED' || output.status === 'FAILED') return;
      }
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
    throw new Error(`Timeout waiting for task ${taskId} to complete`);
  };

  beforeEach(async () => {
    originalCwd = process.cwd();
    originalPath = process.env.PATH || '';

    testDir = mkdtempSync(join(tmpdir(), 'rover-merge-e2e-'));
    process.chdir(testDir);

    mockBinDir = join(testDir, '.mock-bin');
    mkdirSync(mockBinDir, { recursive: true });

    // Create mock HOME directory with agent configuration files
    mockHomeDir = join(testDir, '.mock-home');
    mkdirSync(mockHomeDir, { recursive: true });
    writeFileSync(
      join(mockHomeDir, '.claude.json'),
      JSON.stringify({ version: 1 })
    );

    process.env.PATH = `${mockBinDir}:${originalPath}`;

    createMockTool('docker', 127, 'command not found: docker');
    createMockTool('claude', 127, 'command not found: claude');
    createMockTool('codex', 127, 'command not found: codex');
    createMockTool('cursor', 127, 'command not found: cursor');
    createMockTool('cursor-agent', 127, 'command not found: cursor-agent');
    createMockTool('gemini', 127, 'command not found: gemini');
    createMockTool('qwen', 127, 'command not found: qwen');

    createMockTool('docker', 0, 'Docker version 24.0.0');
    createMockClaude();

    await execa('git', ['init']);
    await execa('git', ['config', 'user.email', 'test@test.com']);
    await execa('git', ['config', 'user.name', 'Test User']);
    await execa('git', ['config', 'commit.gpgsign', 'false']);

    writeFileSync(
      'package.json',
      JSON.stringify(
        { name: 'test-project', version: '1.0.0', type: 'module' },
        null,
        2
      )
    );
    writeFileSync('README.md', '# Test Project\n');

    await execa('git', ['add', '.']);
    await execa('git', ['commit', '-m', 'Initial commit']);

    await runRover(['init', '--yes']);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    process.env.PATH = originalPath;
    rmSync(testDir, { recursive: true, force: true });
  });

  /**
   * SKIPPED: Tests require real AI agent execution
   *
   * Why skipped:
   *   Merge tests require tasks to reach COMPLETED or FAILED status with actual
   *   code changes committed to the task branch. With mock Docker, containers
   *   don't execute, so no commits are made and there's nothing to merge.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Ensure Docker is running and can pull the rover agent image
   *   3. Ensure a valid AI agent (Claude CLI, Gemini CLI, etc.) is installed and authenticated
   *   4. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "successful merge"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)('successful merge', () => {
    it('should merge task branch into the current branch', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      const result = await runRover(['merge', '1', '--json']);
      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
    });

    it('should include changes from the task branch after merge', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      await runRover(['merge', '1', '--json']);

      // Verify the changes are present in the main worktree
      const filesExist = existsSync(join(testDir, 'hello.sh'));
      expect(filesExist).toBe(true);
    });

    it('should update task status after merge', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      await runRover(['merge', '1', '--json']);

      const inspectResult = await runRover(['inspect', '1', '--json']);
      expect(inspectResult.exitCode).toBe(0);
      const task = JSON.parse(inspectResult.stdout);
      expect(task.status).toBe('MERGED');
    });
  });

  /**
   * SKIPPED: Tests require real AI agent execution
   *
   * Why skipped:
   *   Uncommitted changes detection tests require tasks with actual changes.
   *   With mock Docker, no changes are made.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "uncommitted changes"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)(
    'uncommitted changes detection',
    () => {
      it('should handle uncommitted changes in the main repo', async () => {
        await runRover(['task', '-y', 'Create a hello world script']);
        await waitForTaskCompletion(1);

        // Create uncommitted changes in main repo
        writeFileSync(join(testDir, 'uncommitted.txt'), 'uncommitted content');

        const result = await runRover(['merge', '1', '--json']);
        // Should either fail or warn about uncommitted changes
        expect(result.exitCode).toBeDefined();
      });
    }
  );

  /**
   * SKIPPED: Tests require real AI agent execution
   *
   * Why skipped:
   *   Conflict resolution tests require tasks with actual code changes that conflict
   *   with main branch changes. With mock Docker, no real changes are made.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Ensure Docker is running and can pull the rover agent image
   *   3. Ensure a valid AI agent (Claude CLI, Gemini CLI, etc.) is installed and authenticated
   *   4. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "conflict resolution"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)('conflict resolution', () => {
    it('should detect merge conflicts when task branch conflicts with current branch', async () => {
      // Create a task that modifies a file
      await runRover(['task', '-y', 'Modify the README.md file']);
      await waitForTaskCompletion(1);

      // Modify the same file in the main branch to create a conflict
      writeFileSync(join(testDir, 'README.md'), '# Modified in main branch\n');
      await execa('git', ['add', 'README.md'], { cwd: testDir });
      await execa('git', ['commit', '-m', 'Modify README in main'], {
        cwd: testDir,
      });

      // Attempt to merge - should detect conflict
      const result = await runRover(['merge', '1', '--json']);

      // The merge should report a conflict or handle it
      expect(result.exitCode).toBeDefined();
    });

    it('should invoke AI-powered conflict resolution when conflicts are detected', async () => {
      // Create a task that modifies a file
      await runRover(['task', '-y', 'Add a feature to the code']);
      await waitForTaskCompletion(1);

      // Create a conflicting change in main
      writeFileSync(join(testDir, 'README.md'), '# Conflicting change\n');
      await execa('git', ['add', 'README.md'], { cwd: testDir });
      await execa('git', ['commit', '-m', 'Create conflict'], { cwd: testDir });

      // Attempt merge - AI should attempt to resolve conflicts
      const result = await runRover(['merge', '1', '--json']);

      // Verify the merge command handles conflicts appropriately
      // Either resolving them or providing clear feedback
      expect(result.exitCode).toBeDefined();
      if (result.exitCode !== 0) {
        expect(result.stderr + result.stdout).toMatch(
          /conflict|resolve|cannot merge/i
        );
      }
    });
  });

  /**
   * SKIPPED: Tests require real AI agent execution
   *
   * Why skipped:
   *   Hook execution tests require tasks to complete and merge successfully.
   *   With mock Docker, no merges happen.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "merge hook"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)('hook execution', () => {
    it('should execute onMerge hook after successful merge', async () => {
      const hookLogFile = join(testDir, 'merge-hook.log');
      const roverConfig = JSON.parse(
        readFileSync(join(testDir, 'rover.json'), 'utf8')
      );
      roverConfig.hooks = {
        onMerge: [
          `echo "TASK_ID=$ROVER_TASK_ID BRANCH=$ROVER_TASK_BRANCH" > ${hookLogFile}`,
        ],
      };
      writeFileSync(
        join(testDir, 'rover.json'),
        JSON.stringify(roverConfig, null, 2)
      );

      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      await runRover(['merge', '1', '--json']);

      expect(existsSync(hookLogFile)).toBe(true);
      const hookLog = readFileSync(hookLogFile, 'utf8');
      expect(hookLog).toContain('TASK_ID=');
      expect(hookLog).toContain('BRANCH=');
    });

    it('should receive ROVER_TASK_ID, ROVER_TASK_BRANCH, and ROVER_TASK_TITLE in hook', async () => {
      const hookLogFile = join(testDir, 'merge-hook-vars.log');
      const roverConfig = JSON.parse(
        readFileSync(join(testDir, 'rover.json'), 'utf8')
      );
      roverConfig.hooks = {
        onMerge: [
          `echo "ID=$ROVER_TASK_ID BRANCH=$ROVER_TASK_BRANCH TITLE=$ROVER_TASK_TITLE" > ${hookLogFile}`,
        ],
      };
      writeFileSync(
        join(testDir, 'rover.json'),
        JSON.stringify(roverConfig, null, 2)
      );

      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      await runRover(['merge', '1', '--json']);

      expect(existsSync(hookLogFile)).toBe(true);
      const hookLog = readFileSync(hookLogFile, 'utf8');
      expect(hookLog).toMatch(/ID=\d+/);
      expect(hookLog).toContain('BRANCH=');
      expect(hookLog).toContain('TITLE=');
    });
  });
});
