/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * Any manual changes will be overwritten by the automation.
 *
 * To modify these tests, update the specification files:
 * - /E2E_TESTS.md (root-level testing philosophy and constraints)
 * - /packages/cli/E2E_TESTS.md (CLI-specific test specifications)
 *
 * Then run the /update-e2e-tests command to regenerate this file.
 * ============================================================================
 */

import { beforeEach, afterEach, describe, it, expect } from 'vitest';
import { SKIP_REAL_AGENT_TESTS } from './e2e-utils.js';
import {
  mkdtempSync,
  rmSync,
  writeFileSync,
  readFileSync,
  existsSync,
  mkdirSync,
  chmodSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execa } from 'execa';

/**
 * E2E tests for `rover push` command
 *
 * These tests run the actual rover CLI binary and test the full task push workflow.
 * They mock system tool availability by creating wrapper scripts in a temporary bin directory.
 */

describe('rover push (e2e)', () => {
  let testDir: string;
  let remoteDir: string;
  let originalCwd: string;
  let mockBinDir: string;
  let mockHomeDir: string;
  let originalPath: string;

  const createMockTool = (
    toolName: string,
    exitCode: number = 0,
    output: string = 'mock version 1.0.0'
  ) => {
    const scriptPath = join(mockBinDir, toolName);
    const scriptContent = `#!/usr/bin/env bash\necho "${output}"\nexit ${exitCode}`;
    writeFileSync(scriptPath, scriptContent);
    chmodSync(scriptPath, 0o755);
  };

  const createMockScript = (toolName: string, scriptContent: string) => {
    const scriptPath = join(mockBinDir, toolName);
    writeFileSync(scriptPath, scriptContent);
    chmodSync(scriptPath, 0o755);
  };

  const createMockClaude = () => {
    createMockScript(
      'claude',
      `#!/usr/bin/env bash
if [[ "$1" == "--version" ]]; then
  echo "Claude CLI v1.0.0"
  exit 0
fi

if [[ "$1" == "-p" ]]; then
  PROMPT=$(cat)
  if [[ "$2" == "--output-format" && "$3" == "json" ]]; then
    echo '{"result":"{\\"title\\":\\"Test task\\",\\"description\\":\\"A test task description.\\"}"}'
  else
    echo '{"title":"Test task","description":"A test task description."}'
  fi
  exit 0
fi

echo "Claude CLI v1.0.0"
exit 0
`
    );
  };

  const roverBin = join(__dirname, '../../../dist/index.mjs');

  const runRover = async (args: string[]) => {
    const testPath = `${mockBinDir}:${originalPath}`;
    return execa('node', [roverBin, ...args], {
      cwd: testDir,
      env: {
        PATH: testPath,
        HOME: mockHomeDir,
        USER: process.env.USER,
        TMPDIR: process.env.TMPDIR,
        ROVER_NO_TELEMETRY: '1',
      },
      reject: false,
    });
  };

  const waitForTaskCompletion = async (
    taskId: number,
    timeoutMs: number = 600000
  ): Promise<void> => {
    const startTime = Date.now();
    while (Date.now() - startTime < timeoutMs) {
      const result = await runRover(['inspect', String(taskId), '--json']);
      if (result.exitCode === 0) {
        const output = JSON.parse(result.stdout);
        if (output.status === 'COMPLETED' || output.status === 'FAILED') return;
      }
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
    throw new Error(`Timeout waiting for task ${taskId} to complete`);
  };

  beforeEach(async () => {
    originalCwd = process.cwd();
    originalPath = process.env.PATH || '';

    // Create a bare remote repository
    remoteDir = mkdtempSync(join(tmpdir(), 'rover-push-remote-'));
    await execa('git', ['init', '--bare', remoteDir]);

    testDir = mkdtempSync(join(tmpdir(), 'rover-push-e2e-'));
    process.chdir(testDir);

    mockBinDir = join(testDir, '.mock-bin');
    mkdirSync(mockBinDir, { recursive: true });

    // Create mock HOME directory with agent configuration files
    mockHomeDir = join(testDir, '.mock-home');
    mkdirSync(mockHomeDir, { recursive: true });
    writeFileSync(
      join(mockHomeDir, '.claude.json'),
      JSON.stringify({ version: 1 })
    );

    process.env.PATH = `${mockBinDir}:${originalPath}`;

    createMockTool('docker', 127, 'command not found: docker');
    createMockTool('claude', 127, 'command not found: claude');
    createMockTool('codex', 127, 'command not found: codex');
    createMockTool('cursor', 127, 'command not found: cursor');
    createMockTool('cursor-agent', 127, 'command not found: cursor-agent');
    createMockTool('gemini', 127, 'command not found: gemini');
    createMockTool('qwen', 127, 'command not found: qwen');

    createMockTool('docker', 0, 'Docker version 24.0.0');
    createMockClaude();

    await execa('git', ['init']);
    await execa('git', ['config', 'user.email', 'test@test.com']);
    await execa('git', ['config', 'user.name', 'Test User']);
    await execa('git', ['config', 'commit.gpgsign', 'false']);

    // Add remote
    await execa('git', ['remote', 'add', 'origin', remoteDir], {
      cwd: testDir,
    });

    writeFileSync(
      'package.json',
      JSON.stringify(
        { name: 'test-project', version: '1.0.0', type: 'module' },
        null,
        2
      )
    );
    writeFileSync('README.md', '# Test Project\n');

    await execa('git', ['add', '.']);
    await execa('git', ['commit', '-m', 'Initial commit']);
    await execa('git', ['push', '-u', 'origin', 'master'], {
      cwd: testDir,
    }).catch(() =>
      execa('git', ['push', '-u', 'origin', 'main'], { cwd: testDir })
    );

    await runRover(['init', '--yes']);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    process.env.PATH = originalPath;
    rmSync(testDir, { recursive: true, force: true });
    rmSync(remoteDir, { recursive: true, force: true });
  });

  /**
   * SKIPPED: Tests require real AI agent execution
   *
   * Why skipped:
   *   Push tests require tasks to reach COMPLETED or FAILED status with actual
   *   code changes committed to the task branch. With mock Docker, containers
   *   don't execute, so no commits are made and there's nothing meaningful to push.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Ensure Docker is running and can pull the rover agent image
   *   3. Ensure a valid AI agent (Claude CLI, Gemini CLI, etc.) is installed and authenticated
   *   4. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "push with pending changes"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)('push with pending changes', () => {
    it('should commit and push task branch with provided message', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      const result = await runRover([
        'push',
        '1',
        '-m',
        'feat: add hello world script',
        '--json',
      ]);

      expect(result.exitCode).toBe(0);
      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
    });

    it('should use default commit message if not provided', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      const result = await runRover(['push', '1', '--json']);
      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
    });
  });

  /**
   * SKIPPED: Tests require real AI agent execution
   *
   * Why skipped:
   *   Push without pending changes tests require tasks with committed changes.
   *   With mock Docker, no changes are made.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "push without pending changes"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)('push without pending changes', () => {
    it('should push existing branch without creating a new commit', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      // First push to commit and push
      await runRover([
        'push',
        '1',
        '-m',
        'feat: add hello world script',
        '--json',
      ]);

      // Second push should work without new commit
      const result = await runRover(['push', '1', '--json']);
      expect(result.exitCode).toBe(0);
    });
  });

  /**
   * SKIPPED: Tests require real AI agent execution
   *
   * Why skipped:
   *   Upstream branch creation tests require actual git push operations.
   *   With mock Docker, no commits are made.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "upstream branch"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)('upstream branch creation', () => {
    it('should automatically create upstream tracking branch', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      const result = await runRover(['push', '1', '--json']);
      expect(result.exitCode).toBe(0);

      // Verify the branch exists on the remote
      const inspectResult = await runRover(['inspect', '1', '--json']);
      const task = JSON.parse(inspectResult.stdout);
      const branchName = task.branchName;

      const gitResult = await execa(
        'git',
        ['ls-remote', '--heads', 'origin', branchName],
        { cwd: testDir, reject: false }
      );
      expect(gitResult.stdout).toContain(branchName);
    });
  });

  /**
   * SKIPPED: Tests require real AI agent execution and a GitHub remote
   *
   * Why skipped:
   *   GitHub PR link tests require tasks to be pushed to a GitHub remote.
   *   With mock Docker and a local bare repo, no GitHub PR links are generated.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Configure a real GitHub repository as the remote
   *   3. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "GitHub PR link"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)('GitHub PR link', () => {
    it('should provide a link for creating a pull request after successful push to GitHub', async () => {
      // Note: This test requires a real GitHub remote to verify PR link output
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      const result = await runRover(['push', '1', '--json']);
      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);

      // When pushed to a GitHub remote, the output should include a PR creation link
      // The prUrl field should contain a GitHub URL for creating a PR
      if (output.prUrl) {
        expect(output.prUrl).toMatch(/github\.com.*\/compare\//);
      }
    });

    it('should include branch comparison URL in push output', async () => {
      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      const result = await runRover(['push', '1', '--json']);
      expect(result.exitCode).toBe(0);

      // Verify the output structure includes PR-related information
      const output = JSON.parse(result.stdout);
      expect(output).toBeDefined();

      // When pushing to GitHub, we expect either prUrl or a message about how to create a PR
      // This depends on whether the remote is a GitHub repo
    });
  });

  /**
   * SKIPPED: Tests require real AI agent execution
   *
   * Why skipped:
   *   Hook execution tests require tasks to complete and push successfully.
   *   With mock Docker, no pushes happen.
   *
   * TODO: To unskip these tests:
   *   1. Set ROVER_E2E_REAL_AGENT=true environment variable
   *   2. Run with: ROVER_E2E_REAL_AGENT=true pnpm e2e-test --grep "push hook"
   */
  describe.skipIf(SKIP_REAL_AGENT_TESTS)('hook execution', () => {
    it('should execute onPush hook after successful push', async () => {
      const hookLogFile = join(testDir, 'push-hook.log');
      const roverConfig = JSON.parse(
        readFileSync(join(testDir, 'rover.json'), 'utf8')
      );
      roverConfig.hooks = {
        onPush: [
          `echo "TASK_ID=$ROVER_TASK_ID BRANCH=$ROVER_TASK_BRANCH" > ${hookLogFile}`,
        ],
      };
      writeFileSync(
        join(testDir, 'rover.json'),
        JSON.stringify(roverConfig, null, 2)
      );

      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      await runRover(['push', '1', '--json']);

      expect(existsSync(hookLogFile)).toBe(true);
      const hookLog = readFileSync(hookLogFile, 'utf8');
      expect(hookLog).toContain('TASK_ID=');
      expect(hookLog).toContain('BRANCH=');
    });

    it('should receive ROVER_TASK_ID, ROVER_TASK_BRANCH, and ROVER_TASK_TITLE in hook', async () => {
      const hookLogFile = join(testDir, 'push-hook-vars.log');
      const roverConfig = JSON.parse(
        readFileSync(join(testDir, 'rover.json'), 'utf8')
      );
      roverConfig.hooks = {
        onPush: [
          `echo "ID=$ROVER_TASK_ID BRANCH=$ROVER_TASK_BRANCH TITLE=$ROVER_TASK_TITLE" > ${hookLogFile}`,
        ],
      };
      writeFileSync(
        join(testDir, 'rover.json'),
        JSON.stringify(roverConfig, null, 2)
      );

      await runRover(['task', '-y', 'Create a hello world script']);
      await waitForTaskCompletion(1);

      await runRover(['push', '1', '--json']);

      expect(existsSync(hookLogFile)).toBe(true);
      const hookLog = readFileSync(hookLogFile, 'utf8');
      expect(hookLog).toMatch(/ID=\d+/);
      expect(hookLog).toContain('BRANCH=');
      expect(hookLog).toContain('TITLE=');
    });
  });
});
