/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * Any manual changes will be overwritten by the automation.
 *
 * To modify these tests, update the specification files:
 * - /docs/E2E_TESTS.md (root-level testing philosophy and constraints)
 * - /packages/cli/E2E_TESTS.md (CLI-specific test specifications)
 *
 * Then run the /update-e2e-tests command to regenerate this file.
 * ============================================================================
 */

import { beforeEach, afterEach, describe, it, expect } from 'vitest';
import { SKIP_MOCK_TESTS } from './e2e-utils.js';
import {
  mkdtempSync,
  rmSync,
  writeFileSync,
  readFileSync,
  mkdirSync,
  chmodSync,
  readdirSync,
  existsSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join } from 'node:path';
import { execa } from 'execa';

describe.skipIf(SKIP_MOCK_TESTS)('rover resume (e2e)', () => {
  let testDir: string;
  let originalCwd: string;
  let mockBinDir: string;
  let mockHomeDir: string;
  let originalPath: string;
  let dockerCallsLog: string;

  const roverBin = join(__dirname, '../../../dist/index.mjs');

  const createMockScript = (toolName: string, scriptContent: string) => {
    const scriptPath = join(mockBinDir, toolName);
    writeFileSync(scriptPath, scriptContent);
    chmodSync(scriptPath, 0o755);
  };

  const createMockDocker = () => {
    createMockScript(
      'docker',
      `#!/usr/bin/env bash
set -euo pipefail

if [[ "\${1:-}" == "info" && "\${2:-}" == "--format" && "\${3:-}" == "json" ]]; then
  echo '{"ServerVersion":"24.0.0"}'
  exit 0
fi

if [[ "\${1:-}" == "image" && "\${2:-}" == "inspect" ]]; then
  if [[ "\${3:-}" == "--format" && "\${4:-}" == "{{.Id}}" ]]; then
    echo "sha256:mock-agent-image"
    exit 0
  fi
  echo "[]"
  exit 0
fi

if [[ "\${1:-}" == "run" && "\${2:-}" == "--entrypoint" && "\${3:-}" == "/bin/cat" ]]; then
  target="\${@: -1}"
  if [[ "$target" == "/etc/passwd" ]]; then
    echo "root:x:0:0:root:/root:/bin/sh"
    exit 0
  fi
  if [[ "$target" == "/etc/group" ]]; then
    echo "root:x:0:"
    exit 0
  fi
  exit 0
fi

if [[ "\${1:-}" == "rm" && "\${2:-}" == "-f" ]]; then
  exit 0
fi

if [[ "\${1:-}" == "create" ]]; then
  printf '%s\\n' "$*" >> "\${DOCKER_CALLS_LOG:-/tmp/rover-docker-calls.log}"
  echo "mock-container-id"
  exit 0
fi

if [[ "\${1:-}" == "start" ]]; then
  echo "\${2:-mock-container-id}"
  exit 0
fi

echo "Docker version 24.0.0"
exit 0
`
    );
  };

  const createMockClaude = () => {
    createMockScript(
      'claude',
      `#!/usr/bin/env bash
if [[ "$1" == "--version" ]]; then
  echo "Claude CLI v1.0.0"
  exit 0
fi

if [[ "$1" == "-p" ]]; then
  if [[ "$2" == "--output-format" && "$3" == "json" ]]; then
    echo '{"result":"{\\"title\\":\\"Resume test task\\",\\"description\\":\\"A task for resume e2e testing\\"}"}'
  else
    echo '{"title":"Resume test task","description":"A task for resume e2e testing"}'
  fi
  exit 0
fi

echo "Claude CLI v1.0.0"
exit 0
`
    );
  };

  const runRover = async (args: string[]) => {
    const testPath = `${mockBinDir}:${originalPath}`;
    return execa('node', [roverBin, ...args], {
      cwd: testDir,
      env: {
        PATH: testPath,
        HOME: mockHomeDir,
        USER: process.env.USER,
        TMPDIR: process.env.TMPDIR,
        DOCKER_CALLS_LOG: dockerCallsLog,
        ROVER_NO_TELEMETRY: '1',
      },
      reject: false,
    });
  };

  const createTask = async (): Promise<{ taskId: number; savedTo: string }> => {
    const taskResult = await runRover([
      'task',
      '-y',
      'Create a task for resume e2e',
      '--json',
    ]);
    expect(taskResult.exitCode).toBe(0);

    const findDescriptionFiles = (rootPath: string): string[] => {
      if (!existsSync(rootPath)) {
        return [];
      }
      const matches: string[] = [];
      const stack = [rootPath];
      while (stack.length > 0) {
        const current = stack.pop();
        if (!current) continue;
        for (const entry of readdirSync(current, { withFileTypes: true })) {
          const fullPath = join(current, entry.name);
          if (entry.isDirectory()) {
            stack.push(fullPath);
            continue;
          }
          if (entry.isFile() && entry.name === 'description.json') {
            matches.push(fullPath);
          }
        }
      }
      return matches;
    };

    const legacyDescriptions = findDescriptionFiles(
      join(testDir, '.rover', 'tasks')
    );
    const centralDescriptions = findDescriptionFiles(
      join(mockHomeDir, '.rover', 'data')
    );
    const descriptions = [...legacyDescriptions, ...centralDescriptions];
    expect(descriptions.length).toBeGreaterThan(0);

    const savedTo = descriptions[0];
    const taskId = parseInt(basename(dirname(savedTo)), 10);
    expect(Number.isInteger(taskId) && taskId > 0).toBe(true);

    return { taskId, savedTo };
  };

  beforeEach(async () => {
    originalCwd = process.cwd();
    originalPath = process.env.PATH || '';

    testDir = mkdtempSync(join(tmpdir(), 'rover-resume-e2e-'));
    process.chdir(testDir);

    mockBinDir = join(testDir, '.mock-bin');
    mkdirSync(mockBinDir, { recursive: true });

    mockHomeDir = join(testDir, '.mock-home');
    mkdirSync(mockHomeDir, { recursive: true });
    writeFileSync(
      join(mockHomeDir, '.claude.json'),
      JSON.stringify({ version: 1 })
    );

    dockerCallsLog = join(testDir, 'docker-calls.log');
    writeFileSync(dockerCallsLog, '', 'utf8');

    createMockDocker();
    createMockClaude();

    process.env.PATH = `${mockBinDir}:${originalPath}`;

    await execa('git', ['init']);
    await execa('git', ['config', 'user.email', 'test@test.com']);
    await execa('git', ['config', 'user.name', 'Test User']);
    await execa('git', ['config', 'commit.gpgsign', 'false']);

    writeFileSync(
      'package.json',
      JSON.stringify(
        { name: 'resume-e2e-project', version: '1.0.0', type: 'module' },
        null,
        2
      )
    );
    writeFileSync('README.md', '# Resume E2E Test\n');

    await execa('git', ['add', '.']);
    await execa('git', ['commit', '-m', 'Initial commit']);

    const initResult = await runRover(['init', '--yes']);
    expect(initResult.exitCode).toBe(0);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    process.env.PATH = originalPath;
    rmSync(testDir, { recursive: true, force: true });
  });

  it('fails when task is not in PAUSED or FAILED status', async () => {
    const { taskId, savedTo } = await createTask();

    const result = await runRover(['resume', String(taskId), '--json']);
    expect(result.exitCode).not.toBe(0);

    const taskAfterResumeAttempt = JSON.parse(readFileSync(savedTo, 'utf8'));
    expect(taskAfterResumeAttempt.status).not.toBe('PAUSED');
    expect(taskAfterResumeAttempt.status).not.toBe('FAILED');
  });

  it('resumes a paused task and passes checkpoint mount args to container startup', async () => {
    const { taskId, savedTo } = await createTask();

    const taskPath = savedTo;
    const task = JSON.parse(readFileSync(taskPath, 'utf8'));
    task.status = 'PAUSED';
    task.error = 'Paused by retryable error';
    writeFileSync(taskPath, `${JSON.stringify(task, null, 2)}\n`, 'utf8');

    const taskDir = dirname(taskPath);
    const checkpointPath = join(taskDir, 'iterations', '1', 'checkpoint.json');
    mkdirSync(join(checkpointPath, '..'), { recursive: true });
    writeFileSync(
      checkpointPath,
      JSON.stringify({
        completedSteps: [{ id: 'step1', name: 'Step 1', output: {} }],
        failedStepId: 'step2',
        isRetryable: true,
      }),
      'utf8'
    );

    const result = await runRover(['resume', String(taskId), '--json']);
    expect(result.exitCode).toBe(0);
    const resumedTask = JSON.parse(readFileSync(taskPath, 'utf8'));
    expect(resumedTask.status).toBe('IN_PROGRESS');

    const dockerCalls = readFileSync(dockerCallsLog, 'utf8')
      .split('\n')
      .filter(line => line.trim());
    const resumeCreateCall = dockerCalls.at(-1) || '';

    expect(resumeCreateCall).toContain('--checkpoint /output/checkpoint.json');
  });
});
