/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * Any manual changes will be overwritten by the automation.
 *
 * To modify these tests, update the specification files:
 * - /E2E_TESTS.md (root-level testing philosophy and constraints)
 * - /packages/cli/E2E_TESTS.md (CLI-specific test specifications)
 *
 * Then run the /update-e2e-tests command to regenerate this file.
 * ============================================================================
 */

import { beforeEach, afterEach, describe, it, expect } from 'vitest';
import {
  mkdtempSync,
  rmSync,
  writeFileSync,
  readFileSync,
  existsSync,
  mkdirSync,
  chmodSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execa } from 'execa';

/**
 * E2E tests for `rover workflows` command group
 *
 * These tests run the actual rover CLI binary and test the full workflow management.
 * They mock system tool availability by creating wrapper scripts in a temporary bin directory.
 */

describe('rover workflows (e2e)', () => {
  let testDir: string;
  let originalCwd: string;
  let mockBinDir: string;
  let mockHomeDir: string;
  let originalPath: string;

  const createMockTool = (
    toolName: string,
    exitCode: number = 0,
    output: string = 'mock version 1.0.0'
  ) => {
    const scriptPath = join(mockBinDir, toolName);
    const scriptContent = `#!/usr/bin/env bash\necho "${output}"\nexit ${exitCode}`;
    writeFileSync(scriptPath, scriptContent);
    chmodSync(scriptPath, 0o755);
  };

  const createMockScript = (toolName: string, scriptContent: string) => {
    const scriptPath = join(mockBinDir, toolName);
    writeFileSync(scriptPath, scriptContent);
    chmodSync(scriptPath, 0o755);
  };

  const createMockClaude = () => {
    createMockScript(
      'claude',
      `#!/usr/bin/env bash
if [[ "$1" == "--version" ]]; then
  echo "Claude CLI v1.0.0"
  exit 0
fi

if [[ "$1" == "-p" ]]; then
  PROMPT=$(cat)
  if [[ "$2" == "--output-format" && "$3" == "json" ]]; then
    echo '{"result":"{\\"title\\":\\"Test task\\",\\"description\\":\\"A test task description.\\"}"}'
  else
    echo '{"title":"Test task","description":"A test task description."}'
  fi
  exit 0
fi

echo "Claude CLI v1.0.0"
exit 0
`
    );
  };

  const roverBin = join(__dirname, '../../../dist/index.mjs');

  const runRover = async (args: string[]) => {
    const testPath = `${mockBinDir}:${originalPath}`;
    return execa('node', [roverBin, ...args], {
      cwd: testDir,
      env: {
        PATH: testPath,
        HOME: mockHomeDir,
        USER: process.env.USER,
        TMPDIR: process.env.TMPDIR,
        ROVER_NO_TELEMETRY: '1',
      },
      reject: false,
    });
  };

  /**
   * Valid workflow YAML with required id and type fields for each step
   */
  const sampleWorkflowYaml = `name: test-workflow
description: A test workflow for e2e testing
version: "1.0"
steps:
  - id: analyze
    name: Analyze
    type: agent
    description: Analyze the codebase
    prompt: "Analyze the codebase and identify improvements"
  - id: implement
    name: Implement
    type: agent
    description: Implement changes
    prompt: "Implement the identified improvements"
`;

  beforeEach(async () => {
    originalCwd = process.cwd();
    originalPath = process.env.PATH || '';

    testDir = mkdtempSync(join(tmpdir(), 'rover-workflows-e2e-'));
    process.chdir(testDir);

    mockBinDir = join(testDir, '.mock-bin');
    mkdirSync(mockBinDir, { recursive: true });

    // Create mock HOME directory with agent configuration files
    mockHomeDir = join(testDir, '.mock-home');
    mkdirSync(mockHomeDir, { recursive: true });
    writeFileSync(
      join(mockHomeDir, '.claude.json'),
      JSON.stringify({ version: 1 })
    );

    process.env.PATH = `${mockBinDir}:${originalPath}`;

    createMockTool('docker', 127, 'command not found: docker');
    createMockTool('claude', 127, 'command not found: claude');
    createMockTool('codex', 127, 'command not found: codex');
    createMockTool('cursor', 127, 'command not found: cursor');
    createMockTool('cursor-agent', 127, 'command not found: cursor-agent');
    createMockTool('gemini', 127, 'command not found: gemini');
    createMockTool('qwen', 127, 'command not found: qwen');

    createMockTool('docker', 0, 'Docker version 24.0.0');
    createMockClaude();

    await execa('git', ['init']);
    await execa('git', ['config', 'user.email', 'test@test.com']);
    await execa('git', ['config', 'user.name', 'Test User']);
    await execa('git', ['config', 'commit.gpgsign', 'false']);

    writeFileSync(
      'package.json',
      JSON.stringify(
        { name: 'test-project', version: '1.0.0', type: 'module' },
        null,
        2
      )
    );
    writeFileSync('README.md', '# Test Project\n');

    await execa('git', ['add', '.']);
    await execa('git', ['commit', '-m', 'Initial commit']);

    await runRover(['init', '--yes']);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    process.env.PATH = originalPath;
    rmSync(testDir, { recursive: true, force: true });
  });

  describe('add workflow from file', () => {
    it('should add a workflow from a local file path', async () => {
      const workflowFile = join(testDir, 'my-workflow.yml');
      writeFileSync(workflowFile, sampleWorkflowYaml);

      const result = await runRover([
        'workflows',
        'add',
        workflowFile,
        '--json',
      ]);

      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
      expect(output.workflow).toBeDefined();
      expect(output.workflow.name).toBeDefined();
      expect(output.workflow.path).toBeDefined();
    });

    it('should allow setting a custom name with --name flag', async () => {
      const workflowFile = join(testDir, 'my-workflow.yml');
      writeFileSync(workflowFile, sampleWorkflowYaml);

      const result = await runRover([
        'workflows',
        'add',
        workflowFile,
        '--name',
        'custom-name',
        '--json',
      ]);

      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
      expect(output.workflow.name).toBe('custom-name');
    });

    it('should save to global store with --global flag', async () => {
      const workflowFile = join(testDir, 'my-workflow.yml');
      writeFileSync(workflowFile, sampleWorkflowYaml);

      const globalName = `e2e-global-${Date.now()}`;
      const result = await runRover([
        'workflows',
        'add',
        workflowFile,
        '--global',
        '--name',
        globalName,
        '--json',
      ]);

      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
      expect(output.workflow.store).toBe('global');

      // Clean up global workflow
      const globalPath = output.workflow.path;
      if (globalPath && existsSync(globalPath)) {
        rmSync(globalPath);
      }
    });
  });

  describe('add workflow from stdin', () => {
    it('should add a workflow from stdin when source is -', async () => {
      const result = await execa(
        'node',
        [
          roverBin,
          'workflows',
          'add',
          '-',
          '--name',
          'stdin-workflow',
          '--json',
        ],
        {
          cwd: testDir,
          env: {
            PATH: `${mockBinDir}:${originalPath}`,
            HOME: mockHomeDir,
            USER: process.env.USER,
            TMPDIR: process.env.TMPDIR,
            ROVER_NO_TELEMETRY: '1',
          },
          input: sampleWorkflowYaml,
          reject: false,
        }
      );

      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
      expect(output.workflow.name).toBe('stdin-workflow');
    });
  });

  describe('list workflows', () => {
    it('should display all available workflows', async () => {
      const result = await runRover(['workflows', 'list', '--json']);

      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
      expect(Array.isArray(output.workflows)).toBe(true);
      // Should at least have the built-in 'swe' workflow
      expect(output.workflows.length).toBeGreaterThanOrEqual(1);
    });

    it('should show workflow name, description, steps, inputs, and source', async () => {
      // Add a custom workflow first
      const workflowFile = join(testDir, 'my-workflow.yml');
      writeFileSync(workflowFile, sampleWorkflowYaml);
      await runRover(['workflows', 'add', workflowFile, '--json']);

      // List workflows
      const result = await runRover(['workflows', 'list', '--json']);
      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.workflows.length).toBeGreaterThanOrEqual(1);

      // Check the built-in swe workflow has key fields
      const sweWorkflow = output.workflows.find(
        (w: { name: string }) => w.name === 'swe'
      );
      expect(sweWorkflow).toBeDefined();
      expect(sweWorkflow.name).toBeDefined();
      expect(sweWorkflow.description).toBeDefined();
      expect(sweWorkflow.source).toBeDefined();
    });

    it('should work with the ls alias', async () => {
      const result = await runRover(['workflows', 'ls', '--json']);

      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
      expect(Array.isArray(output.workflows)).toBe(true);
    });
  });

  describe('inspect workflow', () => {
    it('should display detailed information about a specific workflow', async () => {
      // Inspect the built-in swe workflow
      const result = await runRover(['workflows', 'inspect', 'swe', '--json']);

      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
      expect(output.workflow).toBeDefined();
      expect(output.workflow.name).toBe('swe');
      expect(output.workflow.description).toBeDefined();
    });

    it('should show raw YAML content with --raw flag', async () => {
      const result = await runRover(['workflows', 'inspect', 'swe', '--raw']);

      expect(result.exitCode).toBe(0);
      // Raw output should contain YAML content
      expect(result.stdout).toContain('name:');
      expect(result.stdout).toContain('steps:');
    });

    it('should inspect a workflow directly from a file path', async () => {
      const workflowFile = join(testDir, 'my-workflow.yml');
      writeFileSync(workflowFile, sampleWorkflowYaml);

      const result = await runRover([
        'workflows',
        'inspect',
        workflowFile,
        '--json',
      ]);

      expect(result.exitCode).toBe(0);

      const output = JSON.parse(result.stdout);
      expect(output.success).toBe(true);
      expect(output.workflow).toBeDefined();
      expect(output.workflow.name).toBeDefined();
    });
  });
});
