import { join } from 'node:path';
import { mkdirSync } from 'node:fs';
import { getProjectPath } from 'rover-core';

/** Marker injected into Rover-generated comments for self-comment detection. */
export const ROVER_FOOTER_MARKER = '<summary>Generated by Rover</summary>';

/**
 * Ensures the spans/ and actions/ directories exist for a project.
 * Call once at autopilot startup — individual SpanWriter / ActionWriter
 * instances assume the directories are already present.
 */
export function ensureTraceDirs(projectId: string): void {
  const base = getProjectPath(projectId);
  mkdirSync(join(base, 'spans'), { recursive: true });
  mkdirSync(join(base, 'actions'), { recursive: true });
}
