export type SpanStatus = 'running' | 'completed' | 'failed' | 'error';

/** A unit of execution within the pipeline. Each step creates a span that
 *  records its start time, status, result summary, and any follow-up actions. */
export interface Span {
  id: string;
  version: string;
  timestamp: string;
  step: string;
  parent: string | null;
  status?: SpanStatus;
  completed?: string | null;
  summary: string | null;
  meta: Record<string, unknown>;
  /** The action that was processed to create this span. Null for the root event span. */
  originAction: string | null;
  /** Action IDs generated during this span's execution. */
  newActions: string[];
}

/** An immutable directive telling the pipeline what to do next.
 *  Created by one step and consumed by another. */
export interface Action {
  id: string;
  version: string;
  action: string;
  timestamp: string;
  spanId: string;
  meta: Record<string, unknown>;
  reasoning: string;
}

export type ActionStepStatus = 'completed' | 'running' | 'pending' | 'error';

/** A single entry in an ActionTrace representing one step's execution. */
export interface ActionStep {
  /** The action that was processed to create this step. Null for the root event step. */
  originAction: string | null;
  action: string;
  status: ActionStepStatus;
  timestamp: string;
  reasoning?: string;
  /** The span ID created by this step's execution. */
  spanId?: string;
  /** True when this step is terminal (no follow-up action). */
  terminal?: boolean;
  /** Action IDs generated by this step. */
  newActions?: string[];
}

/** The full execution history of one event flowing through the pipeline.
 *  Groups all steps from event ingestion to final resolution. */
export interface ActionTrace {
  traceId: string;
  summary: string;
  steps: ActionStep[];
  createdAt: string;
  retryCount?: number;
}

export type FetchStatus = 'idle' | 'fetching' | 'done' | 'error';

/** Tracks which event IDs have been processed to prevent duplicates.
 *  Capped at 200 entries with FIFO eviction. */
export interface EventCursor {
  version: string;
  processedEventIds: string[];
  updatedAt: string;
}

/** An action waiting in the queue to be picked up by its target step. */
export interface PendingAction {
  traceId: string;
  actionId: string;
  spanId: string;
  action: string;
  summary: string;
  createdAt: string;
  meta?: Record<string, unknown>;
}

/** Links an action ID to the Rover task and git branch it created. */
export interface TaskMapping {
  taskId: number;
  branchName: string;
  traceId?: string;
  workflowSpanId?: string;
}

/** A paused action waiting for an external condition before resuming. */
export interface WaitEntry {
  traceId: string;
  actionId: string;
  spanId: string;
  waitingFor: string;
  resumeAction: string;
  resumeMeta: Record<string, unknown>;
  eventSummary: string;
  createdAt: string;
}

/** Top-level persistent state: pending queue, task mappings, and wait queue. */
export interface AutopilotState {
  version: string;
  pending: PendingAction[];
  taskMappings?: Record<string, TaskMapping>;
  waitQueue?: WaitEntry[];
  updatedAt: string;
}

/** A single row in the structured audit log (`log.jsonl`). */
export interface AutopilotLogEntry {
  ts: string;
  traceId: string;
  spanId: string;
  actionId: string;
  step: string;
  action: string;
  summary: string;
}

export type ViewMode = 'main' | 'inspector';

export interface LogEntry {
  timestamp: string;
  message: string;
}

export interface TaskInfo {
  id: number;
  title: string;
  status: string;
  progress: number;
  agent: string;
  duration: string;
  iteration: number;
}
