export interface TaskInfo {
  id: number;
  title: string;
  status: string;
  progress: number;
  agent: string;
  duration: string;
  iteration: number;
}

export interface LogEntry {
  timestamp: string;
  message: string;
}

export type FetchStatus = 'idle' | 'fetching' | 'done' | 'error';

export interface GitHubEvent {
  id: string;
  type: string;
  actor: { login: string };
  created_at: string;
  payload: Record<string, any>;
}

export type SpanStatus = 'running' | 'completed' | 'failed' | 'error';

export interface Span {
  id: string;
  version: string;
  timestamp: string;
  step: string;
  parent: string | null;
  status?: SpanStatus;
  completed?: string | null;
  summary: string | null;
  meta: Record<string, any>;
  /** The action that was processed to create this span. Null for the root event span. */
  originAction: string | null;
  /** Action IDs generated during this span's execution. */
  newActions: string[];
}

export interface Action {
  id: string;
  version: string;
  action: string;
  timestamp: string;
  spanId: string;
  meta: Record<string, any>;
  reasoning: string;
}

export interface EventCursor {
  version: string;
  processedEventIds: string[];
  updatedAt: string;
}

export interface PendingAction {
  traceId: string;
  actionId: string;
  spanId: string;
  action: string;
  summary: string;
  createdAt: string;
  meta?: Record<string, any>;
}

export interface CoordinatorDecision {
  action: string;
  confidence: string;
  reasoning: string;
  context: string;
  meta: Record<string, any>;
}

export type ActionStepStatus =
  | 'completed'
  | 'running'
  | 'pending'
  | 'failed'
  | 'error';

export interface ActionStep {
  /** The action that was processed to create this step. Null for the root event step. */
  originAction: string | null;
  action: string;
  status: ActionStepStatus;
  timestamp: string;
  reasoning?: string;
  /** The span ID created by this step's execution. */
  spanId?: string;
  /** True when this step is terminal (no follow-up action). */
  terminal?: boolean;
  /** Action IDs generated by this step. */
  newActions?: string[];
}

export interface ActionTrace {
  traceId: string;
  summary: string;
  steps: ActionStep[];
  createdAt: string;
  retryCount?: number;
}

export type CoordinatorStatus = 'idle' | 'processing' | 'error';
export type PlannerStatus = 'idle' | 'processing' | 'error';
export type WorkflowRunnerStatus = 'idle' | 'processing' | 'error';
export type CommitterStatus = 'idle' | 'processing' | 'error';
export type ResolverStatus = 'idle' | 'processing' | 'error';
export type PusherStatus = 'idle' | 'processing' | 'error';
export type ResolverDecision = 'wait' | 'push' | 'notify' | 'iterate' | 'fail';

export interface ResolverAIResult {
  decision: 'iterate' | 'fail' | 'notify';
  reasoning: string;
  iterate_instructions?: string;
  fail_reason?: string;
}

export interface SummaryAIResult {
  summary: string;
  saveToMemory: boolean;
}

export interface CommitterAIResult {
  status: 'committed' | 'no_changes' | 'failed';
  commit_sha: string | null;
  commit_message: string | null;
  error: string | null;
  recovery_actions_taken: string[];
  summary: string;
}
export interface PusherAIResult {
  status: 'pushed' | 'failed';
  branches_pushed: string[];
  pull_request: {
    url: string | null;
    created: boolean;
    existing: boolean;
  } | null;
  error: string | null;
  summary: string;
}

export interface NotifyAIResult {
  notify: boolean;
  message: string;
  reasoning: string;
}

export type ViewMode = 'main' | 'inspector';

export interface TaskMapping {
  taskId: number;
  branchName: string;
  traceId?: string;
  workflowSpanId?: string;
}

export interface PlanTask {
  title: string;
  workflow: string;
  acceptance_criteria: string[];
  inputs: Record<string, string>;
  context_uris?: string[];
  context: {
    files: string[];
    references: string[];
    depends_on: string | null;
  };
}

export interface PlanResult {
  analysis: string;
  tasks: PlanTask[];
  execution_order: 'parallel' | 'sequential' | 'mixed';
  reasoning: string;
}

export interface WaitEntry {
  traceId: string;
  actionId: string;
  spanId: string;
  waitingFor: string;
  resumeAction: string;
  resumeMeta: Record<string, any>;
  eventSummary: string;
  createdAt: string;
}

export interface AutopilotState {
  version: string;
  pending: PendingAction[];
  taskMappings?: Record<string, TaskMapping>;
  waitQueue?: WaitEntry[];
  updatedAt: string;
}

export interface AutopilotLogEntry {
  ts: string;
  traceId: string;
  spanId: string;
  actionId: string;
  step: string;
  action: string;
  summary: string;
}
